// src/lib/appraisals/audit.ts
export const APPRAISAL_AUDIT_ACTIONS = {
  INSTRUMENT_VERSION_PUBLISHED: "APPRAISAL_INSTRUMENT_VERSION_PUBLISHED",
  CYCLE_REQUESTED: "APPRAISAL_CYCLE_REQUESTED",
  CYCLE_APPROVED: "APPRAISAL_CYCLE_APPROVED",
  CYCLE_OPENED: "APPRAISAL_CYCLE_OPENED",
  CYCLE_EXTENDED: "APPRAISAL_CYCLE_EXTENDED",
  CYCLE_CLOSED: "APPRAISAL_CYCLE_CLOSED",
  CYCLE_REVIEW_STARTED: "APPRAISAL_CYCLE_REVIEW_STARTED",
  CYCLE_RELEASED: "APPRAISAL_CYCLE_RELEASED",
  CYCLE_CANCELLED: "APPRAISAL_CYCLE_CANCELLED",
  PARTICIPANTS_RESOLVED: "APPRAISAL_PARTICIPANTS_RESOLVED",
  PARTICIPANT_REVOKED: "APPRAISAL_PARTICIPANT_REVOKED",
  RESPONSE_DRAFT_SAVED: "APPRAISAL_RESPONSE_DRAFT_SAVED",
  RESPONSE_FINALIZED: "APPRAISAL_RESPONSE_FINALIZED",
  RESPONSE_EXPIRED: "APPRAISAL_RESPONSE_EXPIRED",
  ASSESSMENT_DRAFT_SAVED: "APPRAISAL_ASSESSMENT_DRAFT_SAVED",
  ASSESSMENT_FINALIZED: "APPRAISAL_ASSESSMENT_FINALIZED",
  ASSESSMENT_RETURNED: "APPRAISAL_ASSESSMENT_RETURNED",
  ASSESSMENT_REVISION_CREATED: "APPRAISAL_ASSESSMENT_REVISION_CREATED",
  REVIEW_DECIDED: "APPRAISAL_REVIEW_DECIDED",
  AGGREGATE_GENERATED: "APPRAISAL_AGGREGATE_GENERATED",
  CONFIDENTIAL_IDENTITY_VIEWED: "APPRAISAL_CONFIDENTIAL_IDENTITY_VIEWED",
  NOTIFICATION_QUEUED: "APPRAISAL_NOTIFICATION_QUEUED",
} as const;

export type AppraisalAuditAction =
  (typeof APPRAISAL_AUDIT_ACTIONS)[keyof typeof APPRAISAL_AUDIT_ACTIONS];

export type AppraisalAuditMetadata = {
  reqId: string;
  action: AppraisalAuditAction;
  cycleId?: string | null;
  instrumentCode?: string | null;
  instrumentVersion?: number | null;
  actorRole?: string | null;
  actorAssignmentId?: string | null;
  targetUserId?: string | null;
  targetTenantId?: string | null;
  targetZoneId?: string | null;
  participantId?: string | null;
  responseId?: string | null;
  assessmentId?: string | null;
  reviewId?: string | null;
  reason?: string | null;
  priorStatus?: string | null;
  nextStatus?: string | null;
};
