// prisma/seed/kg1-our-world-and-our-people.ts
//
// Seed the FULL KG1 Our World and Our People curriculum structure
// (subject, strands, substrands, content standards, indicators)
// from the JSON file generated by Gemini.
//
// Run with:
//   cd C:\Users\OWNER\Documents\ayitikope-mis
//   npx ts-node prisma/seed/kg1-our-world-and-our-people.ts

import { PrismaClient } from "@prisma/client";
import fs from "fs";
import path from "path";

const prisma = new PrismaClient();

type KgOwopIndicatorRow = {
  phase: string;
  level: string;
  subjectName: string;
  subjectSlug: string;

  strandCode: string;
  strandTitle: string;

  subStrandCode: string;
  subStrandTitle: string;

  contentStandardCode: string;
  contentStandardText: string;

  indicatorCode: string;
  indicatorText: string;

  exemplarText: string;
  pageNumberInPdf: number;
  notes: string;
};

async function mainReal() {
  // 1. Load the JSON file
  const jsonPath = path.join(
    process.cwd(),
    "prisma",
    "seed",
    "curriculum",
    "kg1-our-world-and-our-people.json"
  );

  if (!fs.existsSync(jsonPath)) {
    console.error("❌ Seed JSON not found at:", jsonPath);
    process.exit(1);
  }

  const raw = fs.readFileSync(jsonPath, "utf8");
  const rows = JSON.parse(raw) as KgOwopIndicatorRow[];

  console.log(
    `📖 Loading KG1 OWOP curriculum from: ${jsonPath}`
  );
  console.log(`   Indicators in JSON: ${rows.length}`);

  if (rows.length === 0) {
    console.error("❌ JSON has no rows. Exiting.");
    process.exit(1);
  }

  // 2. Make sure the CurriculumSubject exists
  const subjectSlug = rows[0].subjectSlug; // "kg1-our-world-and-our-people"
  const subjectName = rows[0].subjectName; // "KG1 Our World and Our People"

  let subject = await prisma.curriculumSubject.findUnique({
    where: { slug: subjectSlug },
  });

  if (!subject) {
    console.log(
      `➕ Creating CurriculumSubject '${subjectName}' (slug='${subjectSlug}')…`
    );
    subject = await prisma.curriculumSubject.create({
      data: {
        name: subjectName,
        slug: subjectSlug,
        // If your model has phase/level fields, we can later
        // write a small script to backfill them.
      },
    });
  } else {
    console.log(
      `✅ Found existing CurriculumSubject '${subject.name}' (slug='${subject.slug}')`
    );
  }

  // Caches so we don't keep re-querying for the same rows
  const strandCache = new Map<string, string>();      // strandCode -> strandId
  const subStrandCache = new Map<string, string>();   // strandCode|subStrandCode -> subStrandId
  const csCache = new Map<string, string>();          // strandCode|subStrandCode|csCode -> contentStandardId

  // 3. Process each indicator row one by one
  for (const row of rows) {
    console.log(
      `\n→ Processing indicator ${row.indicatorCode} (${row.indicatorText})`
    );

    // --- STRAND ---
    const strandKey = row.strandCode;
    let strandId = strandCache.get(strandKey);

    if (!strandId) {
      let strand = await prisma.curriculumStrand.findFirst({
        where: {
          code: row.strandCode,
          subjectId: subject.id,
        },
      });

      if (!strand) {
        console.log(
          `   ➕ Creating CurriculumStrand ${row.strandCode} - "${row.strandTitle}"`
        );
        strand = await prisma.curriculumStrand.create({
          data: {
            code: row.strandCode,
            title: row.strandTitle,
            subject: {
              connect: { id: subject.id },
            },
          },
        });
      } else {
        console.log(
          `   ✅ Reusing existing strand ${strand.code} - "${strand.title}"`
        );
      }

      strandId = strand.id;
      strandCache.set(strandKey, strandId);
    }

    // --- SUBSTRAND ---
    const subStrandKey = `${row.strandCode}|${row.subStrandCode}`;
    let subStrandId = subStrandCache.get(subStrandKey);

    if (!subStrandId) {
      let subStrand = await prisma.curriculumSubStrand.findFirst({
        where: {
          code: row.subStrandCode,
          strandId,
        },
      });

      if (!subStrand) {
        console.log(
          `   ➕ Creating CurriculumSubStrand ${row.subStrandCode} - "${row.subStrandTitle}"`
        );
        subStrand = await prisma.curriculumSubStrand.create({
          data: {
            code: row.subStrandCode,
            title: row.subStrandTitle,
            strand: {
              connect: { id: strandId },
            },
          },
        });
      } else {
        console.log(
          `   ✅ Reusing existing sub-strand ${subStrand.code} - "${subStrand.title}"`
        );
      }

      subStrandId = subStrand.id;
      subStrandCache.set(subStrandKey, subStrandId);
    }

    // --- CONTENT STANDARD ---
    const csKey = `${row.strandCode}|${row.subStrandCode}|${row.contentStandardCode}`;
    let contentStandardId = csCache.get(csKey);

    if (!contentStandardId) {
      let contentStandard =
        await prisma.curriculumContentStandard.findFirst({
          where: {
            code: row.contentStandardCode,
            subStrandId,
          },
        });

      if (!contentStandard) {
        console.log(
          `   ➕ Creating CurriculumContentStandard ${row.contentStandardCode}`
        );
        contentStandard =
          await prisma.curriculumContentStandard.create({
            data: {
              code: row.contentStandardCode,
              description: row.contentStandardText,
              subStrand: {
                connect: { id: subStrandId },
              },
            },
          });
      } else {
        console.log(
          `   🔁 Updating CurriculumContentStandard ${contentStandard.code}`
        );
        contentStandard =
          await prisma.curriculumContentStandard.update({
            where: { id: contentStandard.id },
            data: {
              description: row.contentStandardText,
            },
          });
      }

      contentStandardId = contentStandard.id;
      csCache.set(csKey, contentStandardId);
    }

    // --- INDICATOR ---
    const existingIndicator =
      await prisma.curriculumIndicator.findFirst({
        where: {
          code: row.indicatorCode,
          contentStandardId,
        },
      });

    if (existingIndicator) {
      console.log(
        `   🔁 Updating existing CurriculumIndicator ${existingIndicator.code}`
      );
      await prisma.curriculumIndicator.update({
        where: { id: existingIndicator.id },
        data: {
          description: row.indicatorText,
          // NOTE: your model does NOT have pageNumberInPdf or notes fields,
          // so we intentionally do NOT set them here.
        },
      } as any);
      console.log("   ✅ Indicator updated.");
    } else {
      console.log(
        `   ➕ Creating new CurriculumIndicator ${row.indicatorCode}`
      );
      await prisma.curriculumIndicator.create({
        data: {
          code: row.indicatorCode,
          description: row.indicatorText,
          // NOTE: we do NOT set pageNumberInPdf or notes here either.
          contentStandard: {
            connect: { id: contentStandardId },
          },
        },
      } as any);
      console.log("   ✅ Indicator created.");
    }
  }

  console.log("\n🎉 Done seeding KG1 Our World and Our People curriculum.");
}

mainReal()
  .catch((err) => {
    console.error("❌ Error in KG1 OWOP curriculum seed:", err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
